Feature/auth
dev-afk-now/Posts-New pull request #4
Opened 2021-12-21 14:02 UTC by dev-afk-now

Fixed, updated according to the PR comments

2021-12-21 20:29 UTC, Nikitaix2311 requested changes
Хорошая работа, молодец!

Оставил ещё комментарии, где нужно что-то изменить, или где можно что-либо оптимизировать.

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/AppDelegate.swift
> +            UserDefaults.standard.bool(forKey: "appWasLaunched")
`appWasLaunched `

вынести в константу или enum UserDefaultsKey

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/AppDelegate.swift
> +        if appWasLaunched {
неправильное условие. 
Так кийчейн будет чиститься при каждом входе, кроме первого

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/FormTextField/FormTextField.swift
> +            return false
подумай, как оптимизировать этот свитч

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/SignIn/SignInPresenter.swift
> +    func validateAndAssign()
а почему Assign?

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/SignIn/SignInPresenter.swift
> +    // MARK: - Private vars -
неправильные марки

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/SignIn/SignInViewController.swift
> +    private func setupSuperViewBackground() {
почему супервью?)

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/SignIn/SignInViewController.swift
> +        let approximateItemHeight: CGFloat = 40
approximateItemHeight - почему approximate?
ты задаёшь точную высоту, а не приблизительную

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/SignUp/SignUpViewController.swift
> +    func isTermsOfServiceAccepted(_ value: Bool)
`isTermsOfServiceAccepted`
название метода похоже на название проперти. 
переделать название

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/SignUp/SignUpViewController.swift
> +        let approximateItemHeight: CGFloat = 40
approximate - переименовать

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/SignUp/SignUpViewController.swift
> +    func textFieldDidChangeSelection(_ textField: UITextField) {
textFieldDidChangeSelection
почему didChangeSelection ?

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/TermsOfService/TermsOfServiceRouter.swift
> +protocol TermsOfServiceRouter {
твой WebView экран может использоваться не только для Terms of Service.
зачем так делать?

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Detail/DetailViewController.swift
> +        NSLayoutConstraint.activate([
`NSLayoutConstraint.activate([
             titleLabel.widthAnchor.constraint(greaterThanOrEqualToConstant: 10)
         ])`
         
         вынести в читабельный метод

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Extensions/CollectionViewCells.swift
> +    func registerCell<T: UICollectionViewCell>(of type: T.Type, reuseIdentifier: String) {
можно взять reuseIdentifier из типа класса. 

String(describing: T.self)

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Extensions/DequeueCell.swift
> +
можно взять reuseIdentifier из типа класса. 

String(describing: T.self)

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Alternative Feed/HomeViewController.swift
> +        collection.registerCell(of: CollectionViewCell.self,
` "CollectionCell"`

magicStrings.
прокомментировал выше, как сделать

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Cells/TableViewCell/FeedViewCell.swift
> +    @IBOutlet weak var headlineLabel: UILabel!
`@IBOutlet weak var headlineLabel: UILabel!
     @IBOutlet weak var descriptionLabel: UILabel!
     @IBOutlet weak var showFullPreviewButton: UIButton!
     @IBOutlet weak var likesLabel: UILabel!
     @IBOutlet weak var timestampLabel: UILabel!`
     
     
     аутлеты должны быть приватными

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Cells/TableViewCell/FeedViewCell.swift
> +    // MARK: - Private variables -
не обрабатывается prepareForReuse метод. 
потенциально несёт за собой баги

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/FeedRouter.swift
>          let filterVC = FilterConfigurator.create(delegate: delegate)
`filterVC`

старайся не сокращать названия. делаем код как можно более читабельным

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/FeedViewController.swift
> +        if let cell = tableView.dequeueTableViewCell("TableViewCell", for: indexPath) {
`"TableViewCell"`

magic stings

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Filter/FilterViewController.swift
> +        self.navigationController?.setNavigationBarHidden(false, animated: true)
вынести в метод

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Modules/Filter/FilterViewController.swift
> +    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
`
     override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
         super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
     }

     required init?(coder: NSCoder) {
         super.init(coder: coder)
     }`
     
     пустые методы

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Service/JSONService/JSONService.swift
> +public let accountStorageName = "users"
зачем использовать здесь public? 
тебе откуда-либо ещё нужна эта проперти?

2021-12-21 20:29 UTC, Nikitaix2311 commented on Posts.demo/Service/KeychainService/KeychainService.swift
> +        if !(KeychainService.shared.get(key: kUsername) ?? "").isEmpty,
`!(KeychainService.shared.get(key: kUsername) ?? "").isEmpty,
            !(KeychainService.shared.get(key: kUsername) ?? "").isEmpty`
            
            копипаст - злая штука. 
            найди ошибку

2021-12-22 08:50 UTC, dev-afk-now commented on Posts.demo/Modules/Auth/SignIn/SignInViewController.swift
> +    private func setupSuperViewBackground() {
а почему нет?) Как еще можно называть родительское view?

2021-12-22 08:50 UTC, dev-afk-now commented on Posts.demo/Modules/Auth/SignIn/SignInPresenter.swift
> +    // MARK: - Private vars -
Не придерживался гайдлайнов в отношении:

2021-12-22 09:10 UTC, dev-afk-now commented on Posts.demo/Modules/Auth/SignUp/SignUpViewController.swift
> +    func textFieldDidChangeSelection(_ textField: UITextField) {
Обнаружилась проблема: заполняя поля входа/регистрации и нажимая кнопку подтверждения формы, последний textField не триггерит исполнения метода EndEditting, из-за этого не сохраняет текст из textField в наш UserForm. Иными словами, последний textField не "теряет фокус" когда пользователь нажимает на кнопку подтверждения формы. 
Сделал коммит до и после изменений, так что можно откатиться.

2021-12-22 11:13 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/SignIn/SignInViewController.swift
> +    private func setupSuperViewBackground() {
потому что это не супервью, а главная вью твоего ViewController. 
родительская вью - это super.view

2021-12-22 11:22 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/SignUp/SignUpViewController.swift
> +    func textFieldDidChangeSelection(_ textField: UITextField) {
добавь в самое начала хендлера кнопки view.endEditing(force: true)

2021-12-22 11:42 UTC, Nikitaix2311 commented on Posts.demo/Extensions/CollectionViewCells.swift
> +    func registerCell<T: UICollectionViewCell>(of type: T.Type, reuseIdentifier: String) {
переделать

2021-12-22 11:42 UTC, Nikitaix2311 commented on Posts.demo/Extensions/DequeueCell.swift
> +
переделать

2021-12-22 11:42 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Alternative Feed/HomeViewController.swift
> +        collection.registerCell(of: CollectionViewCell.self,
переделать

2021-12-23 14:36 UTC, Nikitaix2311 requested changes

2021-12-23 14:36 UTC, Nikitaix2311 commented on Posts.demo/Extensions/CollectionViewCells.swift
> +
удалить файл

2021-12-23 14:36 UTC, Nikitaix2311 commented on Posts.demo/Extensions/DequeueCell.swift
> +    func dequeueCollectionViewCell(for indexPath: IndexPath) -> CollectionCell? {
удалить

2021-12-23 14:36 UTC, Nikitaix2311 commented on Posts.demo/Modules/Auth/TermsOfService/WebViewController.swift
>          let myRequest = URLRequest(url: myURL!)
`        let myRequest = URLRequest(url: myURL!)
`

обработать форс анрап!

2021-12-23 14:36 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Cells/TableViewCell/TableCellReusable.swift
> +    static func cell<T: UITableViewCell>(in tableView: UITableView, for indexPath: IndexPath, _ : T.Type) -> T? {
убрать Дженерик

2021-12-23 14:36 UTC, Nikitaix2311 commented on Posts.demo/Modules/Filter/FilterViewController.swift
> +        super.viewDidLoad()
удалить пустой метод

2021-12-23 14:37 UTC, Nikitaix2311 requested changes
хорошая работа! осталось еще пару моментов

2021-12-23 19:01 UTC, Nikitaix2311 requested changes
будь, пожалуйста, внимательнее! 
опять форс анрапы

2021-12-23 19:01 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Cells/CollectionViewCell/CollectionCellRegistrable.swift
> +    static func registerNib<T: UICollectionViewCell>(in tableView: UICollectionView, _: T.Type) {
вот здесь не нужен дженерик. 
можно обойтись `String(describing: self)`

2021-12-23 19:01 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Cells/TableViewCell/PostCell.swift
> +extension PostCell: TableCellRegistrable, TableCellReusable {
если ты будешь использовать дефолтную реализацию протокола, то не обязательно для этого создавать пустой екстеншн. 
достаточно просто после имени класса написать `class PostCell: UITableViewCell, TableCellRegistrable, TableCellReusable`

2021-12-23 19:01 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Cells/TableViewCell/TableCellRegistrable.swift
> +        tableView.register(UINib(nibName: String(describing: T.self),
здесь дженерик не нужен

2021-12-23 19:01 UTC, Nikitaix2311 commented on Posts.demo/Service/ImageRequest/ImageService/ImageService.swift
> +                completion(result!)
опять форс анрап? 

почему не развернуть result в том же guard-e??? 
будь внимательнее!

2021-12-24 08:55 UTC, Nikitaix2311 approved these changes
Отличная работа!!! 
Так держать!

2021-12-24 08:56 UTC, merged