Feature/dynamic feed
dev-afk-now/Posts-New pull request #7
Opened 2021-12-30 12:11 UTC by dev-afk-now

2022-01-04 12:18 UTC, Nikitaix2311 requested changes
отличная работа! 
Есть пару моментов для оптимизации.

2022-01-04 12:18 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Cells/CollectionViewCell/ShortCollectionCell.swift
> +class ShortCollectionCell: FullWidthCollectionViewCell,
можно вынести реализацию пртокола в базовый класс ячейки, и чтоб все ячейки наследовались от неё. 
Схему описывал на доске

2022-01-04 12:18 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Dynamic Feed/DynamicFeedViewController.swift
> +    private var galleryLayout: UICollectionViewFlowLayout {
можно вынести в отдельный класс лейаута для геллери мода

2022-01-04 12:18 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Dynamic Feed/DynamicFeedViewController.swift
> +        collectionView.collectionViewLayout = gridLayout
```
tableView.isHidden = true
        collectionView.isHidden = false
        collectionView.collectionViewLayout = galleryLayout
        collectionView.reloadData()
        collectionView.collectionViewLayout.invalidateLayout()
```

можно вынести в один метод, в который просто будет передаваться лейаут , который сейчас нужно поставить. а так - у тебя два одинаковых метода, в которых меняется только одна переменная

2022-01-04 12:18 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Dynamic Feed/DynamicFeedViewController.swift
> +        collectionView.collectionViewLayout = gridLayout
можно передавать тип enum DisplayMode - а

2022-01-04 12:18 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/FeedPresenter.swift
> +    func changeDisplayMode(index: Int) {
можно передавать не инт, а прям кейс энама. для удобства.

2022-01-04 12:18 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/FeedPresenter.swift
> +        case .list:
аналогично

2022-01-04 12:18 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Dynamic Feed/GridFlowLayout.swift
> +class GridLayout: UICollectionViewFlowLayout {
довольно усложненная реализация, можно было сделать всё гораздо проще. но ок, работает - пусть будет.

2022-01-04 14:50 UTC, dev-afk-now commented on Posts.demo/Modules/Feed/FeedPresenter.swift
> +        case .list:
проигнорировать (Никита)

2022-01-04 14:59 UTC, dev-afk-now commented on Posts.demo/Modules/Feed/Dynamic Feed/GridFlowLayout.swift
> +class GridLayout: UICollectionViewFlowLayout {
Перепишу flowLayout для коллекции, не закрывай пр, пожалуйста

2022-01-05 12:23 UTC, Nikitaix2311 requested changes

2022-01-05 12:23 UTC, Nikitaix2311 commented on Posts.demo/Modules/Feed/Dynamic Feed/DynamicFeedViewController.swift
> +        if presenter.displayMode == .grid {
лучше использовать switch

2022-01-05 12:36 UTC, Nikitaix2311 commented
оставил пару комментов

2022-01-06 10:05 UTC, Nikitaix2311 approved these changes
молодец! отличная работа! можно мержить!

2022-01-06 14:30 UTC, merged